#! /bin/bash
# Short script that wraps clang's LTO invocations to run the LTO separately before the linking stage
# This helps us use an LTO-generated linker script during the linking stage

set -e

# Check for NOOB_BUILD_DIR environment variable
if [ -z "$NOOB_BUILD_DIR" ]; then
    >&2 echo "Error: NOOB_BUILD_DIR environment variable is not set."
    exit 1
fi

NOOB_BUILD_DIR=$(realpath "$NOOB_BUILD_DIR")

# Figure out whether this script was invoked as "noobclang" or "noobclang++"
invocation_name=$(basename "$0")
clang_command="${invocation_name#noob}-15"

# Check if clang_command is empty or invalid
if [[ -z "$clang_command" ]]; then
    >&2 echo "Error: Script should be invoked with a 'noob' prefix, followed by a valid clang command (e.g., 'noobclang', 'noobclang++')."
    exit 1
fi

set -x

# Actual invocation here
$clang_command "$@" -flto -fuse-ld=/usr/bin/ld.lld-15 -Xclang -disable-O0-optnone -Xclang -no-opaque-pointers \
        -Xlinker --load-pass-plugin=${NOOB_BUILD_DIR}/llvm-plugin/libllvmnoob.so -Wl,-plugin-opt=no-opaque-pointers \
        -Wl,-rpath=${NOOB_BUILD_DIR}/allocator/ ${NOOB_BUILD_DIR}/allocator/libnooballoc.so \
        -Wl,-dynamic-linker,${NOOB_BUILD_DIR}/n00bloader/n00bloader
