#! /bin/bash
# Short script that wraps clang's LTO invocations to run the LTO separately before the linking stage
# This helps us use an LTO-generated linker script during the linking stage

set -x
set -e

# Check for NOOB_BUILD_DIR environment variable
if [ -z "$NOOB_BUILD_DIR" ]; then
    echo "Error: NOOB_BUILD_DIR environment variable is not set."
    exit 1
fi

NOOB_BUILD_DIR=$(realpath "$NOOB_BUILD_DIR")

# Figure out whether this script was invoked as "noobclang" or "noobclang++"
invocation_name=$(basename "$0")
clang_command="${invocation_name#noob}-15"

# Check if clang_command is empty or invalid
if [[ -z "$clang_command" ]]; then
    echo "Error: Script should be invoked with a 'noob' prefix, followed by a valid clang command (e.g., 'noobclang', 'noobclang++')."
    exit 1
fi

echo "Using clang command: $clang_command"

# Separate source files (ending in .o) and other arguments
source_files=()
other_args=()

for arg in "$@"; do
    if [[ $arg == *.o ]]; then
        source_files+=("$arg")
    else
        other_args+=("$arg")
    fi
done

echo "Source files: ${source_files[@]}"
echo "Other args: ${other_args[@]}"

# make sure these do not exist to catch any later errors without reusing stale files
rm noob.tmp.0.5.precodegen.bc noob_linker_script.ld || true

# First invocation: create the instrumented bitcode with only source files and LTO options
#   we ignore errors here because we are not linking in all the correct libraries yet
#   any non-linking errors will be caught by the second command, when 'noob.tmp.0.5.precodegen.bc' doesnt exist
$clang_command "$@" -flto -fuse-ld=/usr/bin/ld.lld-15 -Xclang -disable-O0-optnone \
        -Xlinker --load-pass-plugin=${NOOB_BUILD_DIR}/llvm-plugin/libllvmnoob.so -Wl,-plugin-opt=no-opaque-pointers \
        -Wl,-save-temps -o noob.tmp || true

# Second invocation: link with libraries and generated linker script, omitting source files
$clang_command "${other_args[@]}" -fuse-ld=/usr/bin/ld.lld-15 noob.tmp.0.5.precodegen.bc \
        -Wl,-rpath=${NOOB_BUILD_DIR}/allocator/ ${NOOB_BUILD_DIR}/allocator/libnooballoc.so \
        -T noob_linker_script.ld -mcmodel=large -no-pie
