#! /bin/bash
# Short script that wraps clang's LTO invocations to run the LTO separately before the linking stage
# This helps us use an LTO-generated linker script during the linking stage

set -e

# Figure out whether this script was invoked as "noobclang" or "noobclang++"
invocation_name=$(basename "$0")

if [[ "$invocation_name" == *"++" ]]; then
    clang_command="clang++-15"
else
    clang_command="clang-15"
fi

# Check if clang_command is empty or invalid
if [[ -z "$clang_command" ]]; then
    >&2 echo "Error: could not find command: $clang_command"
    exit 1
fi

set -x

# Actual invocation here
$clang_command "$@" -flto -fuse-ld=/usr/bin/ld.lld-15 -Xclang -disable-O0-optnone -Xclang -no-opaque-pointers \
        @NOOB_PLUGIN_FLAGS@ \
        -Wl,-rpath=@CMAKE_BINARY_DIR@/allocator/ @CMAKE_BINARY_DIR@/allocator/libnooballoc.so \
        -Wl,-dynamic-linker,@CMAKE_BINARY_DIR@/n00bloader/n00bloader
